# Generated by Django 3.1.4 on 2023-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230519_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
